name: Lint Code Base on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Changed Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Linter (Flake8)
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Get Changed Files
      id: files
      run: |
        echo "PR base SHA: ${{ github.event.pull_request.base.sha }}"
        echo "PR head SHA: ${{ github.sha }}"
        changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.py$' || echo "")
        echo "Changed Python files: $changed_files"
        if [ -z "$changed_files" ]; then
          echo "No Python files changed"
          exit 0
        fi
        echo "::set-output name=files::${changed_files}"

    - name: Run Linter on Changed Files
      run: |
        changed_files="${{ steps.files.outputs.files }}"
        if [ -n "$changed_files" ]; then
          echo "Running Flake8 on changed files:"
          echo $changed_files
          flake8 $changed_files
        else
          echo "No Python files changed"
