name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Get changed Python files
      id: files
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || echo "")
        echo "Changed Python files: $changed_files"
        if [ -z "$changed_files" ]; then
          echo "No Python files changed"
          exit 0
        fi
        echo "::set-output name=files::$changed_files"

    - name: Run Flake8 on changed files
      if: steps.files.outputs.files
      run: |
        flake8 ${{ steps.files.outputs.files }} --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ${{ steps.files.outputs.files }} --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
