name: Lint Code Base

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Get changed Python files
      id: files
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pull_number = context.payload.pull_request ? context.payload.pull_request.number : null;
          if (pull_number) {
            const result = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number
            });
            const changedFiles = result.data
              .filter(file => file.filename.endsWith('.py'))
              .map(file => file.filename)
              .join(' ');
            console.log('Changed Python files:', changedFiles);
            if (changedFiles) {
              core.setOutput('files', changedFiles);
            } else {
              console.log('No Python files changed');
            }
          } else {
            console.log('This action only runs on pull_request events');

    - name: Run Flake8 on changed files
      if: steps.files.outputs.files
      run: |
        changed_files=${{ steps.files.outputs.files }}
        echo "Running Flake8 on changed files:"
        echo $changed_files
        flake8_output=$(flake8 $changed_files --count --select=E9,F63,F7,F82 --show-source --statistics)
        echo "flake8_output<<EOF" >> $GITHUB_ENV
        echo "$flake8_output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Post results as a comment
      if: env.flake8_output
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const output = `Flake8 Lint Results:\n\`\`\`\n${{ env.flake8_output }}\n\`\`\``;
          const pull_number = context.payload.pull_request ? context.payload.pull_request.number : null;
          if (pull_number) {
            github.issues.createComment({
              issue_number: pull_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
          } else {
            console.log('No pull request context available for commenting.');
